dist: trusty
sudo: required
language: cpp

env:
  global:
    - secure: "GA9ytMTKRWeC1TgARNqvnO94Z5RdpQ0QeF+kvJzFIN+VXOWTGRaVUmsdPqaI/gqs7SLErDvqhTd8DXh8IOTqO50OnGgjnOR1a/gtIRdfecQFwczIZo99HAQ6YLveoR2eoW5xfy6QNQ06nLS2u4YuooL4CFbsuSV2NiP2Yjrr/cmksvvS5WwZjxFitrYWhr0uORhvrh7uF0a2TSG8D5gXLDtWOSH933f756jPWMLPwEJAM/E71iTIYHWM42+vzhHInCyfjsABaSg3oBz+DXeK+IPHw+ZqmbyWafHQfy6fJkyhm5hJzipmieHHcBwT+SBUTmZ1xuxgdBMzAFvjZVuVVLJ6TvuE/moaCUO6Te/1AhjJjHutTQHtxe7gb7h/9GvGEHL7n/eukNHJx4QJ+s0/VQ+5XeDd1k/uUB65irNcWZBHCLCas3twilRnwD+kaaegTPIkePiZ7DDszrshT3P3erjdtxfIL4I9ClGHS0lyNCBeGzCivktH15ICp0xjVffUdSkVpnkAcHJJEAi35bh+kbuYlPjvoUcQWeFLUzF4QZooiScbm1kxfdD6wF6IJptQCZ5sEt7EaXgXvu7tZvr3I6lqKfW6wRpfr8U0yIIUtX0w4TnelWSCd/vTO83dBboQO9xZc6Wh+9S5hSJkZMnZNp+K/SkPu3uNMxJ7Ruz7ujs="
    - AWS_ACCESS_KEY_ID=AKIAIIVZ76HKTK7EJGAA
    - ATMOSFOAM_TOOLS_SRC=$TRAVIS_BUILD_DIR/src
    - DEBFULLNAME="James Shaw"
    - DEBEMAIL=js102@zepler.net

before_install:
  - sudo sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
  - sudo add-apt-repository "http://dl.openfoam.org/ubuntu dev" -y
  - sudo apt-get -qq update

install:
  - sudo apt-get install openfoam-dev devscripts debhelper ruby-dev -y
  - sudo gem install deb-s3

before_script:
  - source /opt/openfoam-dev/etc/bashrc

script: ./dist.sh
