dist: trusty
sudo: required
language: cpp

env:
  global:
    - secure: "nF8E37Z8mVUOYv/d6WxCyk+QwPHhOCzY6uFnaTuaDkMyYiqHaVZZc7zLxsa+aQKtyKH5TT2iWam7ugyaeqYeJHOmVVP72uIHm9En1RWj2aUt+dtQclztxuuWxfAd4GMJ6LB4Fizza1DtQmH4ln0Bm32J1GFxJ1ChfZbZEldOKJ5biodxB3Vl1EBaj45Km2EzsE85VSu8ySVGCbPlUBu1KY0Py602LmQ3PFS6IPbvhRb2Hv7dMv2Dy2yaBiQnC+jLlcHit6b1P/1fz/sbY1Ej9PbP7G1u51/8RfQRxyArcCnlgIPvRe6x2qqhNXaTQrNX2L2HtGZS58VyroTGT/2H65UJ1KsJ0aP+1pYzHyFhjhlSnNZCgDIOT/l1lRQXINX6HXY+MdApam9tg4bLRQ7QabDgXPNcW+vh6iFD5gt/ts6Bf+ZEalm2G9NbcXHoUgAJ1jOz3HFdUJc38B/hFlWGtsDktENKZmbZVkH5gFvAqWOW/t71m5tB9cdIBP6NQ8czbMwHu+KrNO3qd4tAelUHOPjRA2BIPr9leqYCuQHomqalgc88c8rH2UOMTC6G3qqhDOHEor196SNy/DNgykg1gQD9Tx7FwgnvJbLl9XpEb/gsdB7UcBbmUB85WaXpBsq9LcnNaz5iMmeheaKhIsQ2HgDO24JTiD1CpJNX22I3cH4="
    - AWS_ACCESS_KEY_ID=AKIAIIVZ76HKTK7EJGAA
    - ATMOSFOAM_TOOLS_SRC=$TRAVIS_BUILD_DIR/src
    - DEBFULLNAME="James Shaw"
    - DEBEMAIL=js102@zepler.net

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install singularity-container -y

script: ./singularity.sh
