#!/bin/sh
#

if [ "$#" -lt 2 ]
then
   echo usage: eps2gif outFileName.gif list of eps files
   exit
fi

outFile=$1
shift

fileNames=''

while [ "$#" -ne 0 ]
do
f=$1
   fileName=`basename $f`
   dirName=`dirname $f`
   fRoot=`basename $f .eps`
   thisDir=$PWD
   echo creating $dirName/$fRoot.bmp
   cd $dirName
   echo quit | gs -sDEVICE=bmp256 -sPAPERSIZE=a2 -r100 -q -dNOPAUSE -sOutputFile=%stdout% -- $fileName | \
             convert -trim - $fRoot.bmp
   cd $thisDir
   fileNames="$fileNames $dirName/$fRoot.bmp"

   shift

   #pstopnm
done

echo $fileNames

convert -crop 0x0 -set delay 30 $fileNames $outFile

\rm $fileNames

#png16 png16m png256 png48 pnga pngalpha
#bmp256 pbmraw

animate $outFile &
