#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

set -e

makeType=libso

[ -n "$FOAM_EXT_LIBBIN" ] || {
    echo "Error: FOAM_EXT_LIBBIN not set"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

wmake $makeType OpenFOAM
wmake $makeType finiteVolume
wmake $makeType HodgeOps
wmake $makeType sampling
wmake $makeType geometry
wmake $makeType morePrescribedFields
wmake $makeType functionObjects/field
